AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: The tranmere6 stack
Globals:
  Function:
    Timeout: 3
    AutoPublishAlias: live
Parameters:
  Deployment:
    Type: String
    Default: Canary10Percent5Minutes
  S3BucketName:
    Type: String
  SwaggerFile:
    Type: String
    Default: swagger.yaml
  EnvName:
    Type: String
    Default: sit1
    Description: The name of the environment to deploy to
    AllowedValues:
    - sit1
    - pre1
    - prod1
Mappings:
  SpecialFeature1:
    sit1:
      answer: 1
    pre1:
      answer: 1
    prod1:
      answer: 1
Resources:
  RestApi:
    Type: AWS::Serverless::Api
    Properties:
      Cors:
        AllowOrigin: '''*'''
      StageName: Prod
      Name: tranmere6
      GatewayResponses:
        UNAUTHORIZED:
          StatusCode: 401
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: '''*'''
        ACCESS_DENIED:
          StatusCode: 403
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: '''*'''
        INVALID_API_KEY:
          StatusCode: 200
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: '''*'''
              Access-Control-Allow-Headers: '''x-api-key,content-type'''
        MISSING_AUTHENTICATION_TOKEN:
          StatusCode: 403
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: '''*'''
        DEFAULT_5XX:
          StatusCode: 500
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: '''*'''
        RESOURCE_NOT_FOUND:
          StatusCode: 404
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: '''*'''
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location:
              Fn::Join:
              - ''
              - - s3://
                - Ref: S3BucketName
                - /
                - Ref: SwaggerFile
  tranmere6:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://tranmere-web-api/a80d83cc807ae8093c31c670540b091e
      Handler: tranmere6.handler
      Runtime: nodejs12.x
      DeploymentPreference:
        Type:
          Ref: Deployment
        Alarms:
        - Ref: AliasErrorMetricGreaterThanZeroAlarm
        - Ref: LatestVersionErrorMetricGreaterThanZeroAlarm
      Tracing: Active
      Environment:
        Variables:
          EnvironmentName:
            Ref: EnvName
          SpecialFeature:
            Fn::FindInMap:
            - SpecialFeature1
            - Ref: EnvName
            - answer
      Events:
        PageRequest:
          Type: Api
          Properties:
            Path: /
            RestApiId:
              Ref: RestApi
            Method: get
  AliasErrorMetricGreaterThanZeroAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Lambda Function Error > 0
      AlarmActions:
      - Fn::ImportValue: cloudwatch-notifications-prod-SlackSNSTopic
      OKActions:
      - Fn::ImportValue: cloudwatch-notifications-prod-SlackSNSTopic
      InsufficientDataActions:
      - Fn::ImportValue: cloudwatch-notifications-prod-SlackSNSTopic
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
      - Name: Resource
        Value:
          Fn::Sub: ${tranmere6}:live
      - Name: FunctionName
        Value:
          Ref: tranmere6
      EvaluationPeriods: 2
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60
      Statistic: Sum
      Threshold: 0
  LatestVersionErrorMetricGreaterThanZeroAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Lambda Function Error > 0
      AlarmActions:
      - Fn::ImportValue: cloudwatch-notifications-prod-SlackSNSTopic
      OKActions:
      - Fn::ImportValue: cloudwatch-notifications-prod-SlackSNSTopic
      InsufficientDataActions:
      - Fn::ImportValue: cloudwatch-notifications-prod-SlackSNSTopic
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
      - Name: Resource
        Value:
          Fn::Sub: ${tranmere6}
      - Name: FunctionName
        Value:
          Ref: tranmere6
      EvaluationPeriods: 2
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60
      Statistic: Sum
      Threshold: 0
  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      SourceArn:
        Fn::Sub: arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RestApi}/*/GET/
      FunctionName:
        Ref: tranmere6
      Principal: apigateway.amazonaws.com
  StagingBasePathMapping:
    DependsOn: RestApiProdStage
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      BasePath: tranmere6
      DomainName:
        Fn::Sub: api.${EnvName}.tranmere-web.com
      RestApiId:
        Ref: RestApi
      Stage: Prod
Outputs:
  Endpoint:
    Description: API Gateway endpoint URL the endpoint
    Value:
      Fn::Sub: https://api.${EnvName}.tranmere-web.com/tranmere6/
