AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  The tranmere3 stack

Globals:
  Function:
    Timeout: 3
    AutoPublishAlias: live

Parameters:
  EnvironmentName:
    Type: String
    Default: sit1

Resources:     

  tranmere3RestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'POST, GET'"
        AllowHeaders: "'X-Forwarded-For'"
        AllowOrigin: "*"
        AllowCredentials: True
      DefinitionBody:
        swagger: "2.0"
        info:
          description: "This is a description."
          version: "1.0"
          title:
            Ref: AWS::StackName
        tags:
          - name: "example"
            description: "example tag"
        paths:
          "/tranmere3":
            get:
              tags:
                - "example"
              summary: "A summary"
              description: "A description"
              operationId: "tranmerd3"
              produces:
                - "application/json"
              parameters:
                - name: "test"
                  in: "query"
                  description: "A test parameter"
                  required: false
                  type: "integer"
                  format: "int64"
              responses:
                "200":
                  description: "Success"
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${tranmere3Function.Arn}/invocations


  tranmere3Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: tranmere3.handler
      Runtime: nodejs12.x
      Environment:
        Variables:
          EnvironmentName: !Ref 'EnvironmentName'
      Events:
        PageRequest:
          Type: Api
          Properties:
            Path: /
            RestApiId: !Ref tranmere3RestApi
            Method: get

    StagingBasePathMapping:
      DependsOn: tranmere3RestApiProdStage
      Type: AWS::ApiGateway::BasePathMapping
      Properties:
        BasePath: tranmere3
        DomainName: api.sit1.tranmere-web.com
        RestApiId: !Ref tranmere3RestApi
        Stage: Prod

Outputs:
  Endpoint:
    Description: "API Gateway endpoint URL the endpoint"
    Value: "https://api.sit1.tranmere-web.com/tranmere3/"
