AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: The tranmere6 stack
Globals:
  Function:
    Timeout: 3
    AutoPublishAlias: live

Parameters:
  Deployment:
    Type: String
    Default: Canary10Percent5Minutes
  EnvName:
    Type: String
    Default: sit1
    Description: The name of the environment to deploy to
    AllowedValues:
      - local
      - ci1      
      - sit1
      - pre1
      - prod1

# This is not actually used in the template but a really handy snippet to show 
# to the template can define envioronment specific variables 
Mappings:
  SpecialFeature1:
    ci1:
      answer: 1  
    sit1:
      answer: 1      
    pre1:
      answer: 1
    prod1:
      answer: 1   

Resources:     

  RestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Name: tranmere6
      GatewayResponses:
        UNAUTHORIZED:
          StatusCode: 401
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
        ACCESS_DENIED:
          StatusCode: 403
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
        INVALID_API_KEY:
          StatusCode: 200
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
              Access-Control-Allow-Headers: "'x-api-key,content-type'"
        MISSING_AUTHENTICATION_TOKEN:
          StatusCode: 403
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
        DEFAULT_5XX:
          StatusCode: 500
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
        RESOURCE_NOT_FOUND:
          StatusCode: 404
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
      DefinitionUri: swagger.yaml

  tranmere6:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src
      Handler: tranmere6.handler
      Runtime: nodejs12.x
      DeploymentPreference:
        Type: !Ref Deployment
        Alarms:
          - !Ref AliasErrorMetricGreaterThanZeroAlarm
          - !Ref LatestVersionErrorMetricGreaterThanZeroAlarm
      Tracing: Active  
      Environment:
        Variables:
          EnvironmentName: !Ref EnvName
          SpecialFeature: !FindInMap [SpecialFeature1, !Ref EnvName, answer] # Using the environment variable
      Events:
        PageRequest:
          Type: Api
          Properties:
            Path: /
            RestApiId: !Ref RestApi
            Method: get

  AliasErrorMetricGreaterThanZeroAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmDescription: Lambda Function Error > 0
      AlarmActions:
        - !ImportValue cloudwatch-notifications-prod-SlackSNSTopic
      OKActions:
        - !ImportValue cloudwatch-notifications-prod-SlackSNSTopic
      InsufficientDataActions:
        - !ImportValue cloudwatch-notifications-prod-SlackSNSTopic
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: Resource
          Value: !Sub "${tranmere6}:live"
        - Name: FunctionName
          Value: !Ref tranmere6
      EvaluationPeriods: 2
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60
      Statistic: Sum
      Threshold: 0
  LatestVersionErrorMetricGreaterThanZeroAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmDescription: Lambda Function Error > 0
      AlarmActions:
        - !ImportValue cloudwatch-notifications-prod-SlackSNSTopic
      OKActions:
        - !ImportValue cloudwatch-notifications-prod-SlackSNSTopic
      InsufficientDataActions:
        - !ImportValue cloudwatch-notifications-prod-SlackSNSTopic
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: Resource
          Value: !Sub "${tranmere6}"
        - Name: FunctionName
          Value: !Ref tranmere6
      EvaluationPeriods: 2
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60
      Statistic: Sum
      Threshold: 0

  # This shouldn't be necerssary, but API Gateway often seems to lack permission on the lambda when using swagger definitions
  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties: 
      Action: lambda:InvokeFunction
      SourceArn: 
        Fn::Sub: arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RestApi}/*/GET/
      FunctionName: !Ref tranmere6
      Principal: apigateway.amazonaws.com

  StagingBasePathMapping:
    DependsOn: RestApiProdStage
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      BasePath: tranmere6
      DomainName: !Sub "api.${EnvName}.tranmere-web.com"
      RestApiId: !Ref RestApi
      Stage: Prod

Outputs:
  Endpoint:
    Description: "API Gateway endpoint URL the endpoint"
    Value: !Sub "https://api.${EnvName}.tranmere-web.com/tranmere6/"
