AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  The tranmere3 stack

Globals:
  Function:
    Timeout: 3
    AutoPublishAlias: live

Parameters:
  Environment:
    Type: String
    Default: sit1
    Description: The name of the environment to deploy to
    Allowedvalues:
      - sit1
      - pre1
      - prod1

Mappings:
  SpecialFeature1:
    sit1:
      answer: 1      
    pre1:
      answer: 1
    prod1:
      answer: 1      

Resources:     

  tranmere3RestApi:
    Type: AWS::Serverless::Api
    Properties:
      Cors:
        AllowOrigin: "'*'"
  tranmere3Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: tranmere3.handler
      Runtime: nodejs12.x
      Environment:
        Variables:
          Environment: !Ref 'Environment'
          SpecialFeature: !FindInMap[SpecialFeature1, !Ref 'Environment', answer]
      Events:
        PageRequest:
          Type: Api
          Properties:
            Path: /
            RestApiId: !Ref tranmere3RestApi
            Method: get

    StagingBasePathMapping:
      DependsOn: tranmere3RestApisit1Stage
      Type: AWS::ApiGateway::BasePathMapping
      Properties:
        BasePath: tranmere3
        DomainName: !Sub "api.${Environment}.tranmere-web.com"
        RestApiId: !Ref tranmere3RestApi

Outputs:
  Endpoint:
    Description: "API Gateway endpoint URL the endpoint"
    Value: !Sub "https://api.${Environment}.tranmere-web.com/tranmere3/"
